version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=slsl223
      - MYSQL_PASSWORD=slsl223
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 6050:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=slsl223
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.gitez.cc
      - NEXTCLOUD_TRUSTED_PROXIES=cloud.gitez.cc
      - OVERWRITECLIURL=https://cloud.gitez.cc
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=cloud.gitez.cc
